version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
    volumes:
      - ./data:/app/data
      - ./mlflow:/app/mlflow
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  mlflow:
    image: python:3.9-slim
    working_dir: /app
    command: >
      sh -c "pip install mlflow==2.8.1 &&
             mlflow server --host 0.0.0.0 --port 5001 
             --backend-store-uri ./mlflow/tracking 
             --default-artifact-root ./mlflow/artifacts"
    ports:
      - "5001:5001"
    volumes:
      - ./mlflow:/app/mlflow
    environment:
      - MLFLOW_TRACKING_URI=./mlflow/tracking
    restart: unless-stopped
